version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inc-web
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql:5.7
    container_name: inc-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: db

